stages:
  - checkCircleCI
  
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID == null

Check CircleCI:
  stage: checkCircleCI
  image: gitlab-registry.nordstrom.com/cicd/container-image-composer/runtime/nodejs:12.16.3
  script:
    - cd .gitlab-ci
    - npm ci
    - node checkCircleCi.js
