stages:
  - checkCircleCI

Check CircleCI:
  stage: checkCircleCI
  image: gitlab-registry.nordstrom.com/cicd/container-image-composer/runtime/nodejs:12.16.3
  script:
    - cd .gitlab-ci
    - npm install
    - node checkCircleCI.js