stages:
  - checkCircleCI
  
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID == null

include:
  - project: 'CICD/pipeline-templates'
    ref: NRHL-gitlab-circleci
    file: 'templates/circle-ci/jobs.yml'

#test smart commit time 